<<<<<<< HEAD
# Generated by Django 3.1.3 on 2020-12-10 13:21
=======
# Generated by Django 3.1.3 on 2020-12-21 15:58
>>>>>>> 48c93aae2aff1d0a400f289eb6576471f1be919b

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Twitte',
=======
            name='Twitt',
>>>>>>> 48c93aae2aff1d0a400f289eb6576471f1be919b
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
<<<<<<< HEAD
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='twitt', to=settings.AUTH_USER_MODEL)),
=======
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='twitts', to=settings.AUTH_USER_MODEL)),
>>>>>>> 48c93aae2aff1d0a400f289eb6576471f1be919b
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
